layout: website
title: "BELLA"
author: Lucien Pothier
email: lucienpothier06@gmail.com
description: A multinational fashion company built in Boston.
permalink: bella-clothing.com
image: bellalogoblack.png
date: January 10 2023
